platform :ios, '13.0'

target 'iosApp' do
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleUserMessagingPlatform'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # Remove the arm64 exclusion to support Apple Silicon simulators
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
    end
  end
end
